"""add gender to Person

Revision ID: 2c02360772f6
Revises: e17fc3f60489
Create Date: 2021-09-03 21:48:44.518606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c02360772f6'
down_revision = 'e17fc3f60489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('gender', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'gender')
    # ### end Alembic commands ###
