"""fix messages
;
q


Revision ID: 32d4ebd43b9b
Revises: 251d1123fdba
Create Date: 2021-09-11 22:39:37.984033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d4ebd43b9b'
down_revision = '251d1123fdba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_from_user_id'), 'messages', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_messages_to_user_id'), 'messages', ['to_user_id'], unique=False)
    op.drop_index('ix_message_from_user_id', table_name='message')
    op.drop_index('ix_message_to_user_id', table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('from_user_id', sa.INTEGER(), nullable=True),
    sa.Column('to_user_id', sa.INTEGER(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('create_at', sa.DATETIME(), nullable=True),
    sa.Column('update_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_to_user_id', 'message', ['to_user_id'], unique=False)
    op.create_index('ix_message_from_user_id', 'message', ['from_user_id'], unique=False)
    op.drop_index(op.f('ix_messages_to_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_from_user_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
